project_id = "tqdcpatixtuwgaqakrbx"

[functions.manifold-user]
verify_jwt = false

[functions.managram]
verify_jwt = false

[functions.process-repayments]
verify_jwt = false

[functions.cancel-loan]
verify_jwt = false
