project_id = "tqdcpatixtuwgaqakrbx"

[functions.manifold-user]
verify_jwt = false

[functions.managram]
verify_jwt = true

[functions.process-repayments]
verify_jwt = false

[functions.cancel-loan]
verify_jwt = true

[functions.save-api-key]
verify_jwt = true

[functions.process-bond-maturity]
verify_jwt = false

[functions.purchase-bond]
verify_jwt = true

[functions.trade-memecoin]
verify_jwt = true

[functions.create-memecoin]
verify_jwt = true

[functions.purchase-market-item]
verify_jwt = true

[functions.purchase-bond-treasury]
verify_jwt = true

[functions.arbitrage-scan]
verify_jwt = true

[functions.ai-arbitrage]
verify_jwt = true

[functions.arbitrage-notifications]
verify_jwt = true
