project_id = "tqdcpatixtuwgaqakrbx"

[functions.manifold-user]
verify_jwt = false

[functions.managram]
verify_jwt = true

[functions.process-repayments]
verify_jwt = false

[functions.cancel-loan]
verify_jwt = true

[functions.save-api-key]
verify_jwt = true

[functions.process-bond-maturity]
verify_jwt = false
