project_id = "tqdcpatixtuwgaqakrbx"

[functions.process-bond-interest]
verify_jwt = false

[functions.manifold-user]
verify_jwt = false

[functions.process-repayments]
verify_jwt = false

[functions.cancel-loan]
verify_jwt = true

[functions.process-bond-maturity]
verify_jwt = false

[functions.purchase-bond]
verify_jwt = true

[functions.trade-memecoin]
verify_jwt = true

[functions.create-memecoin]
verify_jwt = true

[functions.purchase-market-item]
verify_jwt = true

[functions.purchase-bond-treasury]
verify_jwt = true

[functions.create-donation]
verify_jwt = false

[functions.process-trading-bots]
verify_jwt = false

[functions.create-pending-transaction]
verify_jwt = true

[functions.verify-transactions]
verify_jwt = false

[functions.execute-arbitrage]
verify_jwt = true

[functions.admin-arbitrage-scan]
verify_jwt = true

[functions.execute-index-fund]
verify_jwt = false

[functions.limit-sell-order]
verify_jwt = true

[functions.conditional-buy-order]
verify_jwt = true

[functions.monitor-conditional-orders]
verify_jwt = false
